{
  "type": "issue",
  "issue": {
    "id": 2863360513,
    "node_id": "I_kwDOABII586qq2oB",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31905",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31905/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31905/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/31905/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/31905",
    "number": 31905,
    "state": "open",
    "state_reason": null,
    "title": "ERROR: AcceptBlockHeader: prev block not found",
    "body": "I noticed in debug.log there are numerous such errors. I'm wondering is it meant to be on local server's blockchain storage or it's kind of network error? Blockchain apparently fully synced yet these errors?\n\n2025-02-19T11:39:07Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T11:39:36Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T11:39:43Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T11:40:43Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T11:42:08Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T11:42:17Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T11:42:34Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T11:57:29Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:44:50Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:45:44Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:47:57Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:48:00Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:48:03Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:48:11Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:48:25Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:49:05Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:49:29Z ERROR: AcceptBlockHeader: prev block not found\n2025-02-19T12:49:33Z ERROR: AcceptBlockHeader: prev block not found\n",
    "user": {
      "login": "goodthebest",
      "id": 1715740,
      "node_id": "MDQ6VXNlcjE3MTU3NDA=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1715740?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/goodthebest",
      "html_url": "https://github.com/goodthebest",
      "followers_url": "https://api.github.com/users/goodthebest/followers",
      "following_url": "https://api.github.com/users/goodthebest/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/goodthebest/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/goodthebest/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/goodthebest/subscriptions",
      "organizations_url": "https://api.github.com/users/goodthebest/orgs",
      "repos_url": "https://api.github.com/users/goodthebest/repos",
      "events_url": "https://api.github.com/users/goodthebest/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/goodthebest/received_events",
      "type": "User",
      "site_admin": false,
      "patch_url": null
    },
    "labels": [],
    "assignees": [],
    "author_association": "NONE",
    "locked": false,
    "comments": 0,
    "created_at": "2025-02-19T13:31:41Z",
    "updated_at": "2025-02-19T13:33:45Z"
  },
  "events": []
}