{
  "type": "issue",
  "issue": {
    "id": 2919617624,
    "node_id": "I_kwDOABII586uBdRY",
    "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32066",
    "repository_url": "https://api.github.com/repos/bitcoin/bitcoin",
    "labels_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32066/labels%7B/name%7D",
    "comments_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32066/comments",
    "events_url": "https://api.github.com/repos/bitcoin/bitcoin/issues/32066/events",
    "html_url": "https://github.com/bitcoin/bitcoin/issues/32066",
    "number": 32066,
    "state": "open",
    "state_reason": null,
    "title": "intermittent issue in wallet_reorgsrestore.py in test_reorg_handling_during_unclean_shutdown: FailedToStartError: [node 0] bitcoind exited with status 1 during initialization. Error: Cannot obtain a lock on directory",
    "body": "https://cirrus-ci.com/task/4809537674280960?logs=ci#L2287:\n\n```\n[04:43:25.506]  test  2025-03-14T08:43:24.312000Z TestFramework.utils (DEBUG): Deleting leftover cookie file \n[04:43:25.506]  test  2025-03-14T08:43:24.315000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up \n[04:43:25.506]  test  2025-03-14T08:43:24.576000Z TestFramework (ERROR): Unexpected exception caught during testing \n[04:43:25.506]                                    Traceback (most recent call last):\n[04:43:25.506]                                      File \"/ci_container_base/test/functional/test_framework/test_framework.py\", line 135, in main\n[04:43:25.506]                                        self.run_test()\n[04:43:25.506]                                      File \"/ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/test/functional/wallet_reorgsrestore.py\", line 216, in run_test\n[04:43:25.506]                                        self.test_reorg_handling_during_unclean_shutdown()\n[04:43:25.506]                                      File \"/ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/test/functional/wallet_reorgsrestore.py\", line 121, in test_reorg_handling_during_unclean_shutdown\n[04:43:25.506]                                        self.start_node(0)\n[04:43:25.506]                                      File \"/ci_container_base/test/functional/test_framework/test_framework.py\", line 567, in start_node\n[04:43:25.506]                                        node.wait_for_rpc_connection()\n[04:43:25.506]                                      File \"/ci_container_base/test/functional/test_framework/test_node.py\", line 275, in wait_for_rpc_connection\n[04:43:25.506]                                        raise FailedToStartError(self._node_msg(\n[04:43:25.506]                                    test_framework.test_node.FailedToStartError: [node 0] bitcoind exited with status 1 during initialization. Error: Cannot obtain a lock on directory /ci_container_base/ci/scratch/test_runner/test_runner_‚Çø_üèÉ_20250314_083240/wallet_reorgsrestore_195/node0/regtest. Bitcoin Core is probably already running.\n[04:43:25.506]                                    ************************\n[04:43:25.506]  test  2025-03-14T08:43:24.579000Z TestFramework (DEBUG): Closing down network thread \n[04:43:25.506]  test  2025-03-14T08:43:24.663000Z TestFramework (INFO): Not stopping nodes as test failed. The dangling processes will be cleaned up later. \n[04:43:25.506]  test  2025-03-14T08:43:24.663000Z TestFramework (WARNING): Not cleaning up dir /ci_container_base/ci/scratch/test_runner/test_runner_‚Çø_üèÉ_20250314_083240/wallet_reorgsrestore_195 \n[04:43:25.506]  test  2025-03-14T08:43:24.663000Z TestFramework (ERROR): Test failed. Test logging available at /ci_container_base/ci/scratch/test_runner/test_runner_‚Çø_üèÉ_20250314_083240/wallet_reorgsrestore_195/test_framework.log \n[04:43:25.506]  test  2025-03-14T08:43:24.663000Z TestFramework (ERROR): \n[04:43:25.506]  test  2025-03-14T08:43:24.664000Z TestFramework (ERROR): Hint: Call /ci_container_base/test/functional/combine_logs.py '/ci_container_base/ci/scratch/test_runner/test_runner_‚Çø_üèÉ_20250314_083240/wallet_reorgsrestore_195' to consolidate all logs \n[04:43:25.506]  test  2025-03-14T08:43:24.664000Z TestFramework (ERROR): \n[04:43:25.506]  test  2025-03-14T08:43:24.664000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log. \n[04:43:25.506]  test  2025-03-14T08:43:24.664000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues \n[04:43:25.506]  test  2025-03-14T08:43:24.664000Z TestFramework (ERROR): \n[04:43:25.506] \n[04:43:25.506]  node0 stderr Error: Cannot obtain a lock on directory /ci_container_base/ci/scratch/test_runner/test_runner_‚Çø_üèÉ_20250314_083240/wallet_reorgsrestore_195/node0/regtest. Bitcoin Core is probably already running. \n[04:43:25.518] ",
    "user": {
      "login": "maflcko",
      "id": 6399679,
      "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/maflcko",
      "html_url": "https://github.com/maflcko",
      "followers_url": "https://api.github.com/users/maflcko/followers",
      "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
      "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
      "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
      "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
      "organizations_url": "https://api.github.com/users/maflcko/orgs",
      "repos_url": "https://api.github.com/users/maflcko/repos",
      "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
      "received_events_url": "https://api.github.com/users/maflcko/received_events",
      "type": "User",
      "site_admin": false,
      "patch_url": null
    },
    "labels": [
      {
        "id": 5334691551,
        "node_id": "LA_kwDOABII588AAAABPfju3w",
        "url": "https://api.github.com/repos/bitcoin/bitcoin/labels/CI%20failed",
        "name": "CI failed",
        "description": "",
        "color": "cccccc",
        "default": false
      }
    ],
    "assignees": [],
    "author_association": "MEMBER",
    "locked": false,
    "comments": 0,
    "created_at": "2025-03-14T08:51:58Z",
    "updated_at": "2025-03-14T09:13:40Z"
  },
  "events": [
    {
      "event": "labeled",
      "id": 16768521439,
      "node_id": "LE_lADOABII586uBdRYzwAAAAPne1Tf",
      "url": "https://api.github.com/repos/bitcoin/bitcoin/issues/events/16768521439",
      "actor": {
        "login": "maflcko",
        "id": 6399679,
        "node_id": "MDQ6VXNlcjYzOTk2Nzk=",
        "avatar_url": "https://avatars.githubusercontent.com/u/6399679?v=4",
        "gravatar_id": "",
        "url": "https://api.github.com/users/maflcko",
        "html_url": "https://github.com/maflcko",
        "followers_url": "https://api.github.com/users/maflcko/followers",
        "following_url": "https://api.github.com/users/maflcko/following%7B/other_user%7D",
        "gists_url": "https://api.github.com/users/maflcko/gists%7B/gist_id%7D",
        "starred_url": "https://api.github.com/users/maflcko/starred%7B/owner%7D%7B/repo%7D",
        "subscriptions_url": "https://api.github.com/users/maflcko/subscriptions",
        "organizations_url": "https://api.github.com/users/maflcko/orgs",
        "repos_url": "https://api.github.com/users/maflcko/repos",
        "events_url": "https://api.github.com/users/maflcko/events%7B/privacy%7D",
        "received_events_url": "https://api.github.com/users/maflcko/received_events",
        "type": "User",
        "site_admin": false,
        "patch_url": null
      },
      "commit_id": null,
      "commit_url": null,
      "created_at": "2025-03-14T09:13:40Z",
      "label": {
        "name": "CI failed",
        "color": "cccccc"
      }
    }
  ]
}